# Generated by Django 5.2.16 on 2026-07-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'ordering': ['-created_at']},
        ),
    ]
