# Generated by Django 5.2.16 on 2026-07-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_catalog', '0002_alter_api_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='api',
            name='slug',
            field=models.SlugField(),
        ),
    ]
