# Generated by Django 5.2.16 on 2026-07-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_catalog', '0003_alter_api_name_alter_api_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiversion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
