# Generated by Django 5.2.16 on 2026-07-17 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_catalog', '0004_api_is_deleted_apiversion_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiversion',
            name='version',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Version must be in a format like 'v1', 'v2', 'v1.0', or 'v1.0.1'.", regex='^v\\d+(\\.\\d+)*$')]),
        ),
    ]
