# Generated by Django 5.2.16 on 2026-07-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(max_length=64),
        ),
    ]
