"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

"""

from pathlib import Path
from decouple import config
from datetime import timedelta

# -----------------------------------------------------------------------------
# Base Configuration
# -----------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent.parent

SECRET_KEY = config("SECRET_KEY")

# -----------------------------------------------------------------------------
# Installed Applications
# -----------------------------------------------------------------------------

INSTALLED_APPS = [
    # Django Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third Party Apps
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",
    "corsheaders",

    # Local Apps
    "apps.accounts",
    "apps.api_catalog",
    "apps.subscriptions",
    "apps.developer_projects",
    "apps.api_keys",
    "apps.usage_logs",
    "apps.dashboard",
    "apps.notifications",
    "apps.core",
]

# -----------------------------------------------------------------------------
# Middleware
# -----------------------------------------------------------------------------

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# -----------------------------------------------------------------------------
# URLs
# -----------------------------------------------------------------------------

ROOT_URLCONF = "config.urls"

# -----------------------------------------------------------------------------
# Templates
# -----------------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# -----------------------------------------------------------------------------
# WSGI
# -----------------------------------------------------------------------------

WSGI_APPLICATION = "config.wsgi.application"

# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
    }
}

API_VERSION = "1.0.0"
CACHE_TTL = 60 * 15  # 15 minutes

# -----------------------------------------------------------------------------
# Redis Cache Configuration
# -----------------------------------------------------------------------------

REDIS_HOST = config("REDIS_HOST", default="127.0.0.1")
REDIS_PORT = config("REDIS_PORT", default="6379", cast=int)
REDIS_DB = config("REDIS_DB", default="1", cast=int)
REDIS_URL = config("REDIS_URL", default=f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "protocol": 2,
            },
        },
    }
}

# -----------------------------------------------------------------------------
# Password Validation
# -----------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# -----------------------------------------------------------------------------
# Internationalization
# -----------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# -----------------------------------------------------------------------------
# Static & Media
# -----------------------------------------------------------------------------

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# -----------------------------------------------------------------------------
# Default Primary Key
# -----------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------------------------------------------------------------
# Django REST Framework
# -----------------------------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": (
        "apps.core.pagination.StandardResultsSetPagination"
    ),
    "PAGE_SIZE": 10,

    "EXCEPTION_HANDLER": "apps.core.exceptions.custom_exception_handler",
}

# -----------------------------------------------------------------------------
# Swagger
# -----------------------------------------------------------------------------

SPECTACULAR_SETTINGS = {
    "TITLE": "APIHub API",
    "DESCRIPTION": "Enterprise API Developer Portal",
    "VERSION": "1.0.0",

    # Hide the schema endpoint from Swagger UI
    "SERVE_INCLUDE_SCHEMA": False,

    # Generate separate request and response schemas
    "COMPONENT_SPLIT_REQUEST": True,

    # Custom TAGS order for Swagger UI
    "TAGS": [
        {
            "name": "Authentication",
            "description": "User registration, authentication, token refresh, logout, and profile management.",
        },
        {
            "name": "Developers",
            "description": "Developer user account management endpoints (Admin only).",
        },
        {
            "name": "Health Check",
            "description": "System health and status monitoring endpoints.",
        },
        {
            "name": "API Catalog",
            "description": "API Catalog management endpoints.",
        },
        {
            "name": "API Versions",
            "description": "API Versioning management endpoints.",
        },
        {
            "name": "API Endpoints",
            "description": "API Endpoint specifications and metadata.",
        },
        {
            "name": "API Documentation",
            "description": "API Documentation endpoints.",
        },
        {
            "name": "Developer Projects",
            "description": "Developer project management endpoints.",
        },
        {
            "name": "Subscription Plans",
            "description": "Subscription plan management endpoints.",
        },
        {
            "name": "User Subscriptions",
            "description": "Developer user subscription lifecycle endpoints.",
        },
        {
            "name": "API Keys",
            "description": "Developer API Key management and protected sample endpoints.",
        },
        {
            "name": "Usage Logs",
            "description": "API Usage log querying and history endpoints.",
        },
        {
            "name": "Dashboard",
            "description": "Analytics dashboard endpoints for admins and developers.",
        },
    ],

    # Explicit Enum names to resolve naming collisions for status fields
    "ENUM_NAME_OVERRIDES": {
        "APIStatusEnum": "apps.api_catalog.models.API.Status",
        "UserSubscriptionStatusEnum": "apps.subscriptions.models.UserSubscription.Status",
    },
}



AUTH_USER_MODEL = "accounts.User"


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}