"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

"""

from pathlib import Path
import sys
from decouple import config
from datetime import timedelta

# -----------------------------------------------------------------------------
# Base Configuration
# -----------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent.parent

SECRET_KEY = config("SECRET_KEY")

# -----------------------------------------------------------------------------
# Installed Applications
# -----------------------------------------------------------------------------

INSTALLED_APPS = [
    # ASGI Server : it used to run Django with ASGI support for WebSockets and other protocols
    # ASGI server that accepts HTTP and WebSocket connections.
    # Daphne is an ASGI server.
    # Every HTTP request and every WebSocket connection first reaches Daphne.
    "daphne",

    # Django Apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third Party Apps
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "django_filters",
    "corsheaders",
    "channels",       # Django Channels for WebSocket support

    # Local Apps
    "apps.accounts",
    "apps.api_catalog",
    "apps.subscriptions",
    "apps.developer_projects",
    "apps.api_keys",
    "apps.usage_logs",
    "apps.dashboard",
    "apps.notifications",
    "apps.core",
]

# -----------------------------------------------------------------------------
# Middleware
# -----------------------------------------------------------------------------

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# -----------------------------------------------------------------------------
# URLs
# -----------------------------------------------------------------------------

ROOT_URLCONF = "config.urls"

# -----------------------------------------------------------------------------
# Templates
# -----------------------------------------------------------------------------

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# -----------------------------------------------------------------------------
# WSGI & ASGI
# -----------------------------------------------------------------------------

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

# -----------------------------------------------------------------------------
# Database
# -----------------------------------------------------------------------------

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
    }
}

API_VERSION = "1.0.0"
CACHE_TTL = 60 * 15  # 15 minutes

# -----------------------------------------------------------------------------
# Redis Cache Configuration
# -----------------------------------------------------------------------------

REDIS_HOST = config("REDIS_HOST", default="127.0.0.1")
REDIS_PORT = config("REDIS_PORT", default="6379", cast=int)
REDIS_DB = config("REDIS_DB", default="1", cast=int)
REDIS_URL = config("REDIS_URL", default=f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "protocol": 2,
            },
        },
    }
}

# -----------------------------------------------------------------------------
# Celery Configuration
# -----------------------------------------------------------------------------

import redis
import redis.asyncio

# Patch synchronous and asynchronous redis-py ConnectionPool to use RESP2 protocol by default.
# This prevents 'unknown command HELLO' error when connecting to Redis < 6.0 / Windows Redis.
_orig_pool_init = redis.ConnectionPool.__init__


def _patched_pool_init(self, *args, **kwargs):
    kwargs.setdefault("protocol", 2)
    _orig_pool_init(self, *args, **kwargs)


redis.ConnectionPool.__init__ = _patched_pool_init

try:
    _orig_async_pool_init = redis.asyncio.connection.ConnectionPool.__init__


    def _patched_async_pool_init(self, *args, **kwargs):
        kwargs.setdefault("protocol", 2)
        _orig_async_pool_init(self, *args, **kwargs)


    redis.asyncio.connection.ConnectionPool.__init__ = _patched_async_pool_init
except Exception:
    pass

# Redis acts as the Message Broker (queue) where enqueued tasks are stored.
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default=f"redis://{REDIS_HOST}:{REDIS_PORT}/0")

# Redis acts as the Result Backend where task execution results/statuses are stored.
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default=f"redis://{REDIS_HOST}:{REDIS_PORT}/0")

from celery.schedules import crontab

# Use JSON format for serializing task data safely.
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

# -----------------------------------------------------------------------------
# Celery Beat Periodic Tasks Schedule
# -----------------------------------------------------------------------------
# Celery Beat acts as a cron-like scheduler. It reads this dictionary and enqueues
# task messages into Redis automatically at specified intervals or crontab times.
CELERY_BEAT_SCHEDULE = {
    # 1. Generate Daily Platform Report every day at Midnight (12:00 AM UTC)
    "generate-daily-report-every-midnight": {
        "task": "apps.core.tasks.generate_daily_report",
        "schedule": crontab(minute=0, hour=0),
    },
    # 2. Check and send Subscription Reminders every day at 8:00 AM UTC
    "check-subscription-reminders-every-morning": {
        "task": "apps.core.tasks.check_subscription_reminders",
        "schedule": crontab(minute=0, hour=8),
    },
}


# -----------------------------------------------------------------------------
# Channel Layers (Django Channels Redis backend with test fallback)
# -----------------------------------------------------------------------------

if "test" in sys.argv or config("USE_IN_MEMORY_CHANNEL_LAYER", default=False, cast=bool):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.pubsub.RedisPubSubChannelLayer",
            "CONFIG": {
                "hosts": [
                    config("REDIS_URL", default=f"redis://{REDIS_HOST}:{REDIS_PORT}/0"),
                ],
            },
        },
    }

# -----------------------------------------------------------------------------
# Password Validation
# -----------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# -----------------------------------------------------------------------------
# Internationalization
# -----------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Explicitly align Celery timezone with Django's TIME_ZONE setting.
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# -----------------------------------------------------------------------------
# Static & Media
# -----------------------------------------------------------------------------

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# -----------------------------------------------------------------------------
# Default Primary Key
# -----------------------------------------------------------------------------

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------------------------------------------------------------
# Django REST Framework
# -----------------------------------------------------------------------------

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_FILTER_BACKENDS": (
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": (
        "apps.core.pagination.StandardResultsSetPagination"
    ),
    "PAGE_SIZE": 10,

    "EXCEPTION_HANDLER": "apps.core.exceptions.custom_exception_handler",
}

# -----------------------------------------------------------------------------
# Swagger
# -----------------------------------------------------------------------------

SPECTACULAR_SETTINGS = {
    "TITLE": "APIHub API",
    "DESCRIPTION": "Enterprise API Developer Portal",
    "VERSION": "1.0.0",

    # Hide the schema endpoint from Swagger UI
    "SERVE_INCLUDE_SCHEMA": False,

    # Generate separate request and response schemas
    "COMPONENT_SPLIT_REQUEST": True,

    # Custom TAGS order for Swagger UI
    "TAGS": [
        {
            "name": "Authentication",
            "description": "User registration, authentication, token refresh, logout, and profile management.",
        },
        {
            "name": "Developers",
            "description": "Developer user account management endpoints (Admin only).",
        },
        {
            "name": "Health Check",
            "description": "System health and status monitoring endpoints.",
        },
        {
            "name": "API Catalog",
            "description": "API Catalog management endpoints.",
        },
        {
            "name": "API Versions",
            "description": "API Versioning management endpoints.",
        },
        {
            "name": "API Endpoints",
            "description": "API Endpoint specifications and metadata.",
        },
        {
            "name": "API Documentation",
            "description": "API Documentation endpoints.",
        },
        {
            "name": "Developer Projects",
            "description": "Developer project management endpoints.",
        },
        {
            "name": "Subscription Plans",
            "description": "Subscription plan management endpoints.",
        },
        {
            "name": "User Subscriptions",
            "description": "Developer user subscription lifecycle endpoints.",
        },
        {
            "name": "API Keys",
            "description": "Developer API Key management and protected sample endpoints.",
        },
        {
            "name": "Usage Logs",
            "description": "API Usage log querying and history endpoints.",
        },
        {
            "name": "Dashboard",
            "description": "Analytics dashboard endpoints for admins and developers.",
        },
    ],

    # Explicit Enum names to resolve naming collisions for status fields
    "ENUM_NAME_OVERRIDES": {
        "APIStatusEnum": "apps.api_catalog.models.API.Status",
        "UserSubscriptionStatusEnum": "apps.subscriptions.models.UserSubscription.Status",
    },
}



AUTH_USER_MODEL = "accounts.User"


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}