# Generated by Django 5.2.16 on 2026-07-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagelog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='usagelog',
            name='requested_at',
        ),
    ]
