# Generated by Django 5.2.16 on 2026-07-23 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_logs', '0002_alter_usagelog_options_remove_usagelog_requested_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagelog',
            options={'ordering': ['-requested_at']},
        ),
        migrations.AddField(
            model_name='usagelog',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 23, 12, 18, 46, 132218, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
